import { BN } from '@coral-xyz/anchor';
import { toToken } from './CommonUtils';

const DAYS_IN_A_MONTH = 30;
const DAYS_IN_A_QUARTER = 90;
const DAYS_IN_A_HALF_YEAR = 180;
const DAYS_IN_A_YEAR = 360;
const JUNIOR_TRANCHE = 0;
const SENIOR_TRANCHE = 1;
const DEFAULT_DECIMALS_FACTOR = new BN(10).pow(new BN(18));
const MONTHS_IN_A_YEAR = 12;
const SECONDS_IN_A_DAY = 24 * 60 * 60;
const SECONDS_IN_A_WEEK = 24 * 60 * 60 * 7;
const HUNDRED_PERCENT_BPS = new BN(10_000);
const MIN_POOL_BALANCE_FOR_REDEMPTION = toToken(10);
const MIN_DEPOSIT_AMOUNT = toToken(10);

export const CONSTANTS = {
  DAYS_IN_A_MONTH,
  DAYS_IN_A_QUARTER,
  DAYS_IN_A_HALF_YEAR,
  DAYS_IN_A_YEAR,
  JUNIOR_TRANCHE,
  SENIOR_TRANCHE,
  DEFAULT_DECIMALS_FACTOR,
  MONTHS_IN_A_YEAR,
  SECONDS_IN_A_DAY,
  SECONDS_IN_A_WEEK,
  HUNDRED_PERCENT_BPS,
  MIN_POOL_BALANCE_FOR_REDEMPTION,
  MIN_DEPOSIT_AMOUNT
};
